# Generated by Django 3.1.2 on 2020-10-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receitas', '0020_auto_20201024_0328'),
        ('usuarios', '0006_auto_20201025_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('acao_tomar', models.CharField(max_length=300)),
                ('data_categoria', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('data_denuncia', models.DateField(auto_now_add=True)),
                ('categoria_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_denuncia', to='usuarios.usuario')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_denuncia', to='receitas.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denuncia', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaComentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('comentario', models.TextField()),
                ('data_denuncia', models.DateField(auto_now_add=True)),
                ('CategoriaDenuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_denuncia', to='denuncias.categoriadenuncia')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncia_receita', to='receitas.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncia_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
