# Generated by Django 3.1.2 on 2020-10-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201025_1254'),
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denunciareceita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='categoriadenuncia',
            name='descricao',
            field=models.TextField(default='MUITO ADULTO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denunciareceita',
            name='usuario_denunciado',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denunciado_receita', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denunciareceita',
            name='usuario_efetuou_denuncia',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DenunciaComentarios',
        ),
    ]
