# Generated by Django 3.1.2 on 2020-10-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201025_1254'),
        ('denuncias', '0002_auto_20201026_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciareceita',
            name='categoria_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_denuncia', to='denuncias.categoriadenuncia'),
        ),
        migrations.AlterField(
            model_name='denunciareceita',
            name='usuario_efetuou_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_efetuou_denuncia', to='usuarios.usuario'),
        ),
    ]
