# Generated by Django 3.1.2 on 2020-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_auto_20201026_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciareceita',
            name='situacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
