# Generated by Django 3.1.2 on 2020-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_auto_20201026_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadenuncia',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
