# Generated by Django 3.1.2 on 2020-11-11 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncias', '0006_categoriadenuncia_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciareceita',
            name='usuario_denunciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denunciado_receita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denunciareceita',
            name='usuario_efetuou_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_efetuou_denuncia', to=settings.AUTH_USER_MODEL),
        ),
    ]
