# Generated by Django 3.1.2 on 2020-10-24 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='data_comentario',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
