# Generated by Django 3.1.2 on 2020-10-25 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0020_auto_20201024_0328'),
        ('comentarios', '0002_auto_20201024_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='receitas.receita'),
        ),
    ]
