# Generated by Django 3.1.2 on 2020-10-13 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('categoria_chefe', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=60)),
                ('foto_usuario', models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/')),
                ('dt_criacao', models.DateField(blank=True, default=datetime.datetime.now)),
                ('dt_alteracao', models.DateField(blank=True)),
            ],
        ),
    ]
