# Generated by Django 3.1.2 on 2020-10-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria_chefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria_chefe.categoriachefe'),
        ),
    ]
