# Generated by Django 3.1.2 on 2020-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_dt_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria_chefe',
            field=models.CharField(max_length=200),
        ),
    ]
