# Generated by Django 3.1.2 on 2020-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201025_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria_chefe',
            field=models.CharField(choices=[('Leig', 'Leigo'), ('Inic', 'Iniciante'), ('Inte', 'Intermediário'), ('Avan', 'Avançado'), ('Prof', 'Profissional')], default='Leig', max_length=25),
        ),
    ]
