# Generated by Django 3.1.2 on 2020-11-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20201102_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_pessoa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
