# Generated by Django 3.1.2 on 2020-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20201110_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(default='Um chefe muito valente em busca de gloria'),
            preserve_default=False,
        ),
    ]
