# Generated by Django 3.1.2 on 2020-11-16 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0013_usuario_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avaliacao',
            field=models.ManyToManyField(related_name='avaliacao_chefe', to=settings.AUTH_USER_MODEL),
        ),
    ]
