# Generated by Django 3.1.2 on 2020-10-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.TextField(default='descricao'),
            preserve_default=False,
        ),
    ]
