# Generated by Django 3.1.2 on 2020-10-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20201014_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='categoria',
            new_name='categoria_chefe',
        ),
    ]
