# Generated by Django 3.1.2 on 2020-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20201014_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria_chefe',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='dt_alteracao',
        ),
        migrations.AddField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
