# Generated by Django 3.1.2 on 2020-10-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_auto_20201014_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='avaliacao_receita',
            field=models.FloatField(blank=True, default='0'),
            preserve_default=False,
        ),
    ]
