# Generated by Django 3.1.2 on 2020-10-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_auto_20201014_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='avaliacao_receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='avaliacao',
            field=models.FloatField(default=0),
        ),
    ]
