# Generated by Django 3.1.2 on 2020-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_auto_20201014_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='avaliacao',
            field=models.FloatField(blank=True),
        ),
    ]
