# Generated by Django 3.1.2 on 2020-10-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_auto_20201014_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='avaliacao',
        ),
    ]
