# Generated by Django 3.1.2 on 2020-10-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_remove_receita_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='avaliacao',
            field=models.FloatField(default=0),
        ),
    ]
