# Generated by Django 3.1.2 on 2020-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0013_auto_20201018_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='avaliacao',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_estimado',
            field=models.TextField(),
        ),
    ]
