# Generated by Django 3.1.2 on 2020-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0014_auto_20201018_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.TextField(default='BENGALA'),
            preserve_default=False,
        ),
    ]
