# Generated by Django 3.1.2 on 2020-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_receita_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita2',
            field=models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='foto_receita3',
            field=models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/'),
        ),
    ]
