# Generated by Django 3.1.2 on 2020-10-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0016_auto_20201018_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
