# Generated by Django 3.1.2 on 2020-10-24 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0018_auto_20201023_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
