# Generated by Django 3.1.2 on 2020-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0019_auto_20201024_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.TextField(default='DEKDEOPKDPWEOKDPWOE'),
            preserve_default=False,
        ),
    ]
