# Generated by Django 3.1.2 on 2020-11-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0020_auto_20201024_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingrediente', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='avaliacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Bolos e Tortas', 'Bolos e Tortas'), ('Carnes', 'Carnes'), ('Aves', 'Aves'), ('Peixes e Frutos do Mar', 'Peixes e Frutos do Mar'), ('Saladas e Molhos', 'Saladas e Molhos'), ('Sopas', 'Sopas'), ('Massas', 'Massas'), ('Bebidas', 'Bebidas'), ('Doces e Sobremesas', 'Doces e Sobremesas'), ('Lanches', 'Lanches'), ('Fitness', 'Fitness'), ('Outros', 'Outros')], max_length=200),
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_estimado',
            field=models.CharField(choices=[('Até R$ 50,00', 'Até R$ 50,00'), ('Entre R$ 50,00 e R$ 100,00', 'Entre R$ 50,00 e R$ 100,00'), ('Entre R$ 100,00 e R$ 150,00', 'Entre R$ 100,00 e R$ 150,00'), ('Entre R$ 150,00 e R$ 200,00', 'Entre R$ 150,00 e R$ 200,00'), ('Superior a R$ 200,00', 'Superior a R$ 200,00')], max_length=200),
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(to='receitas.Ingredientes'),
        ),
    ]
