# Generated by Django 3.1.2 on 2020-11-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0024_auto_20201105_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Bolos e Tortas', 'Bolos e Tortas'), ('Carnes', 'Carnes'), ('Aves', 'Aves'), ('Peixes e Frutos do Mar', 'Peixes e Frutos do Mar'), ('Saladas e Molhos', 'Saladas e Molhos'), ('Sopas', 'Sopas'), ('Massas', 'Massas'), ('Bebidas', 'Bebidas'), ('Doces e Sobremesas', 'Doces e Sobremesas'), ('Lanches', 'Lanches'), ('Fitness', 'Fitness'), ('Outros', 'Outros')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Profissional', 'Profissional')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(choices=[('Até 5 pessoas', 'Até 5 pessoas'), ('Até 10 pessoas', 'Até 10 pessoas'), ('Até 15 pessoas', 'Até 15 pessoas'), ('Até 20 pessoas', 'Até 20 pessoas'), ('Até 50 pessoas', 'Até 50 pessoas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(choices=[('Até 10 minutos', 'Até 10 minutos'), ('Até 20 minutos,', 'Até 20 minutos,'), ('Até 30 minutos', 'Até 30 minutos'), ('Até 60 minutos', 'Até 60 minutos'), ('Superior 60 minutos', 'Superior 60 minutos')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_estimado',
            field=models.CharField(choices=[('Até R$ 50,00', 'Até R$ 50,00'), ('Entre R$ 50,00 e R$ 100,00', 'Entre R$ 50,00 e R$ 100,00'), ('Entre R$ 100,00 e R$ 150,00', 'Entre R$ 100,00 e R$ 150,00'), ('Entre R$ 150,00 e R$ 200,00', 'Entre R$ 150,00 e R$ 200,00'), ('Superior a R$ 200,00', 'Superior a R$ 200,00')], max_length=200),
        ),
    ]
