# Generated by Django 3.1.2 on 2020-11-06 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0026_auto_20201105_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='receita_publicada', to=settings.AUTH_USER_MODEL),
        ),
    ]
