# Generated by Django 3.1.2 on 2020-11-10 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0027_auto_20201105_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='likes',
            field=models.ManyToManyField(related_name='receita_publicada', to=settings.AUTH_USER_MODEL),
        ),
    ]
