# Generated by Django 3.1.2 on 2020-11-10 14:41

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0029_auto_20201110_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Bolos e Tortas', 'Bolos e Tortas'), ('Carnes', 'Carnes'), ('Aves', 'Aves'), ('Peixes e Frutos do Mar', 'Peixes e Frutos do Mar'), ('Saladas e Molhos', 'Saladas e Molhos'), ('Sopas', 'Sopas'), ('Massas', 'Massas'), ('Bebidas', 'Bebidas'), ('Doces e Sobremesas', 'Doces e Sobremesas'), ('Lanches', 'Lanches'), ('Fitness', 'Fitness'), ('Outros', 'Outros')], max_length=250),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Profissional', 'Profissional')], max_length=250),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_receita2',
            field=models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='foto_receita3',
            field=models.ImageField(blank=True, upload_to='static/fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='likes',
            field=models.ManyToManyField(related_name='receita_publicada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(choices=[('Até 10 minutos', 'Até 10 minutos'), ('Até 20 minutos,', 'Até 20 minutos,'), ('Até 30 minutos', 'Até 30 minutos'), ('Até 60 minutos', 'Até 60 minutos'), ('Superior 60 minutos', 'Superior 60 minutos')], max_length=250),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_estimado',
            field=models.CharField(choices=[('Até R$ 50,00', 'Até R$ 50,00'), ('Entre R$ 50,00 e R$ 100,00', 'Entre R$ 50,00 e R$ 100,00'), ('Entre R$ 100,00 e R$ 150,00', 'Entre R$ 100,00 e R$ 150,00'), ('Entre R$ 150,00 e R$ 200,00', 'Entre R$ 150,00 e R$ 200,00'), ('Superior a R$ 200,00', 'Superior a R$ 200,00')], max_length=250),
        ),
    ]
