# Generated by Django 3.1.2 on 2020-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0030_auto_20201110_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(default='LALALALALA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default='LALALALALAL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(choices=[('Até 5 pessoas', 'Até 5 pessoas'), ('Até 10 pessoas', 'Até 10 pessoas'), ('Até 15 pessoas', 'Até 15 pessoas'), ('Até 20 pessoas', 'Até 20 pessoas'), ('Até 50 pessoas', 'Até 50 pessoas')], max_length=250),
        ),
    ]
