# Generated by Django 3.1.2 on 2020-11-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0031_auto_20201113_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_x_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
